production: true
seo: true
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "Gemfile", "prod.rb", "fonts"]
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: []

sass:
  style: compressed

# Site settings
title: "Wilderhood: Recitals"
header-img: img/home-bg.jpg
email: contact@wilderhood.com
description: "Travel community for wildlife destinations"
baseurl: ""

url: "http://recitals.wilderhood.com"
#url: "http://127.0.0.1:4000"
twitter_username: https://twitter.com/wilderhood
github_username1:  https://github.com/wilderhood
facebook_username:  https://www.facebook.com/wilderhood
googleplay_name: http://bit.ly/whoodplaystore
iosappstore_name: http://bit.ly/whooditunes
disqus-shortname: wilderhoodrecitals
domain-home: "wilderhood.com"

# Build settings
markdown: kramdown
highlighter: pygments
# permalink: pretty
relative_permalinks: false
paginate: 10

collections:
  wildart:
    output: true

gems:
  - jekyll-sitemap