production: false
seo: false
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "Gemfile", "prod.rb"]
include: ["_cssdev", "_jsdev"]
compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  ignore:
    envs: ['development']

# Site settings
title: "Wilderhood: Recitals"
header-img: img/home-bg.jpg
email: contact@wilderhood.com
description: "Travel community for wildlife destinations"
baseurl: ""

url: "http://recitals.wilderhood.com"
#url: "http://127.0.0.1:4000"
twitter_username: https://twitter.com/wilderhood
github_username1:  https://github.com/wilderhood
facebook_username:  https://www.facebook.com/wilderhood
googleplay_name: http://bit.ly/whoodplaystore
iosappstore_name: http://bit.ly/whooditunes
disqus-shortname: wilderhoodrecitals
domain-home: "wilderhood.com"

# Build settings
markdown: kramdown
# permalink: pretty
relative_permalinks: false
paginate: 10

collections:
  wildart:
    output: true
  wildlifeweek:
    output: true
  MajesticStripes:
    output: true
  laughingdove:
    output: true
  africandiaries:
    output: true

gems:
  - jekyll-sitemap
  - jekyll-paginate