require 'uglifier'

File.open("./_includes/gallery.autogenerated.js", 'w') { |file| file.write(Uglifier.new(:enclose => false).compile(File.read("./_jsdev/gallery.js"))) }
File.open("./_includes/clean-blog.autogenerated.js", 'w') { |file| file.write(Uglifier.new(:enclose => false).compile(File.read("./_jsdev/clean-blog.js"))) }
File.open("./js/seo.autogenerated.js", 'w') { |file| file.write(Uglifier.new(:enclose => false).compile(File.read("./_jsdev/seo.js"))) }